name: Ether
version: 0.0.0
api-version: 1.19
main: org.minerift.ether.EtherPlugin
author: Avaerian
commands:
  nmschunk:
    description: Debug command for clearing chunks via NMS
  nmsblock:
    description: Debug command for setting chunks via NMS
  pasteschem:
    description: Debug command for pasting a schematic