# GitHub Action for running unit tests and building jar
# TODO: deploy to test docker container and run integrated tests

name: dev

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          
      #- name: Validate Gradle wrapper
      #  uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      #- name: Change wrapper permissions
      #  run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.8'
      - name: Build with Gradle
        run: gradle shadowJar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs/
