# GitHub Action for running unit tests and building jar
# TODO: deploy to test docker container and run integrated tests

name: Development

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar


      # Testing uploading artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs